# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35b6485e738278ca1b81cad4d038c77d6ea2bdb3f75a3acdf22a4d2d280448106ae389fccdd875ed3a5494b5cc1deb84133784ee9e5740008254c67d94bed5e7

test:
  secret_key_base: 48da3454d5902adf18a97ce0b21b9ba4de3e6eae3b8dadecfe18a723976ade759602c17f267535b48621145dde20d407892ecc7a109eda851a21aa367a58f5a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
